//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFilenames", ReplyAction="http://tempuri.org/IService1/getFilenamesResponse")]
        string[] getFilenames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFilenames", ReplyAction="http://tempuri.org/IService1/getFilenamesResponse")]
        System.Threading.Tasks.Task<string[]> getFilenamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStream", ReplyAction="http://tempuri.org/IService1/GetStreamResponse")]
        System.IO.Stream GetStream(string filepath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStream", ReplyAction="http://tempuri.org/IService1/GetStreamResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetStreamAsync(string filepath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFileLength", ReplyAction="http://tempuri.org/IService1/getFileLengthResponse")]
        long getFileLength(string filepath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFileLength", ReplyAction="http://tempuri.org/IService1/getFileLengthResponse")]
        System.Threading.Tasks.Task<long> getFileLengthAsync(string filepath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getFilenames() {
            return base.Channel.getFilenames();
        }
        
        public System.Threading.Tasks.Task<string[]> getFilenamesAsync() {
            return base.Channel.getFilenamesAsync();
        }
        
        public System.IO.Stream GetStream(string filepath) {
            return base.Channel.GetStream(filepath);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetStreamAsync(string filepath) {
            return base.Channel.GetStreamAsync(filepath);
        }
        
        public long getFileLength(string filepath) {
            return base.Channel.getFileLength(filepath);
        }
        
        public System.Threading.Tasks.Task<long> getFileLengthAsync(string filepath) {
            return base.Channel.getFileLengthAsync(filepath);
        }
    }
}
